### ISSUE TITLE
Option to add prefixes to generated bindings.

### ISSUE THREAD

**Issue by CGrahamS** [hbb20/butterknife-code-generator#1]
Hey there!

Love this tool.
Not having any issues with the generator, I just had a thought.

What if you implemented the option to add a prefix to the generated variables?

For example:
`android:id="@+id/loginTextView"` becomes `    @Bind(R.id.loginTextView) TextView mLoginTextView;`

Thanks for making this!

**Comment by hbb20** [comment]
Hey @CGrahamS , Thanks for suggestion. I've added suggested option in my new tool [AVB (Android View Binding) Code Generator](https://goo.gl/4vwI2L). Please check it. Hope it will help you,
