### ISSUE TITLE
Update it according to new version of ButterKnife

### ISSUE THREAD

**Issue by rajsuvariya** [hbb20/butterknife-code-generator#2]

**Comment by hbb20** [comment]
Nice to see that you are using this but now you can switch to the new tool. Please try new [Android View Binding Code Generator](https://hbb20.github.io/AVB-CodeGenerator/) which has support for latest butterknife code. 

Additionally, it also supports basic code generation for activity, fragments and butterknife library module code.

**Comment by rajsuvariya** [comment]
Thanks
